#!/usr/bin/env python

# run as python script

import sys
import argparse

# the raw args from the cmd line
print(sys.argv)

parser = argparse.ArgumentParser()

# required positional arg
parser.add_argument("arg1", type=int,
                    help="arg1")

# 2nd required positional arg
parser.add_argument("arg2", type=str,
                    help="arg2")

# optional '-' flag with no arg
parser.add_argument("-v", "--verbose", help="increase output verbosity",
                    action="store_true")

# optional '-' flag no arg
parser.add_argument("-q", "--query", help="query for exit value",
			 action='store_true')

# optional '-' flag with required arg
parser.add_argument("-e", "--exit", help="increase output verbosity",
			 type=int)



# parsed args - will automatically print errors and abort on bad args
args = parser.parse_args()
#print(type(args))
#print(args)

print('arg1=', args.arg1)
print('arg2=', args.arg2)

# args.verbose will = None if no arg
if args.verbose:
    print("verbosity turned on")

if args.exit:
   print("exit with:", args.exit)
   # in bash, print with:  echo $?
   sys.exit(args.exit)
   print("won't get here")

if args.query:
   # demand input from the user
   es = input('specify exit value: ')
   e = int(es)
   sys.exit(e)

